// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// addis_sync_faster
DataFrame addis_sync_faster(NumericVector pval, NumericVector gammai, double lambda, double alpha, double tau, double w0);
RcppExport SEXP _onlineFDR_addis_sync_faster(SEXP pvalSEXP, SEXP gammaiSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP tauSEXP, SEXP w0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammai(gammaiSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    rcpp_result_gen = Rcpp::wrap(addis_sync_faster(pval, gammai, lambda, alpha, tau, w0));
    return rcpp_result_gen;
END_RCPP
}
// addis_async_faster
DataFrame addis_async_faster(NumericVector pval, IntegerVector E, NumericVector gammai, double lambda, double alpha, double tau, double w0);
RcppExport SEXP _onlineFDR_addis_async_faster(SEXP pvalSEXP, SEXP ESEXP, SEXP gammaiSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP tauSEXP, SEXP w0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type E(ESEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammai(gammaiSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    rcpp_result_gen = Rcpp::wrap(addis_async_faster(pval, E, gammai, lambda, alpha, tau, w0));
    return rcpp_result_gen;
END_RCPP
}
// alphainvesting_faster
DataFrame alphainvesting_faster(NumericVector pval, NumericVector gammai, double alpha, double w0);
RcppExport SEXP _onlineFDR_alphainvesting_faster(SEXP pvalSEXP, SEXP gammaiSEXP, SEXP alphaSEXP, SEXP w0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammai(gammaiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    rcpp_result_gen = Rcpp::wrap(alphainvesting_faster(pval, gammai, alpha, w0));
    return rcpp_result_gen;
END_RCPP
}
// lond_faster
DataFrame lond_faster(NumericVector pval, NumericVector betai, double alpha, bool original);
RcppExport SEXP _onlineFDR_lond_faster(SEXP pvalSEXP, SEXP betaiSEXP, SEXP alphaSEXP, SEXP originalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betai(betaiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type original(originalSEXP);
    rcpp_result_gen = Rcpp::wrap(lond_faster(pval, betai, alpha, original));
    return rcpp_result_gen;
END_RCPP
}
// londstar_async_faster
DataFrame londstar_async_faster(NumericVector pval, IntegerVector E, NumericVector betai, double alpha);
RcppExport SEXP _onlineFDR_londstar_async_faster(SEXP pvalSEXP, SEXP ESEXP, SEXP betaiSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type E(ESEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betai(betaiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(londstar_async_faster(pval, E, betai, alpha));
    return rcpp_result_gen;
END_RCPP
}
// londstar_dep_faster
DataFrame londstar_dep_faster(NumericVector pval, IntegerVector L, NumericVector betai, double alpha);
RcppExport SEXP _onlineFDR_londstar_dep_faster(SEXP pvalSEXP, SEXP LSEXP, SEXP betaiSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betai(betaiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(londstar_dep_faster(pval, L, betai, alpha));
    return rcpp_result_gen;
END_RCPP
}
// londstar_batch_faster
List londstar_batch_faster(NumericVector pval, IntegerVector batch, IntegerVector batchsum, NumericVector betai, double alpha);
RcppExport SEXP _onlineFDR_londstar_batch_faster(SEXP pvalSEXP, SEXP batchSEXP, SEXP batchsumSEXP, SEXP betaiSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type batch(batchSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type batchsum(batchsumSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type betai(betaiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(londstar_batch_faster(pval, batch, batchsum, betai, alpha));
    return rcpp_result_gen;
END_RCPP
}
// lord_faster
DataFrame lord_faster(NumericVector pval, NumericVector gammai, int version, double alpha, double w0, double b0, double taudiscard);
RcppExport SEXP _onlineFDR_lord_faster(SEXP pvalSEXP, SEXP gammaiSEXP, SEXP versionSEXP, SEXP alphaSEXP, SEXP w0SEXP, SEXP b0SEXP, SEXP taudiscardSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammai(gammaiSEXP);
    Rcpp::traits::input_parameter< int >::type version(versionSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< double >::type taudiscard(taudiscardSEXP);
    rcpp_result_gen = Rcpp::wrap(lord_faster(pval, gammai, version, alpha, w0, b0, taudiscard));
    return rcpp_result_gen;
END_RCPP
}
// lordstar_async_faster
DataFrame lordstar_async_faster(NumericVector pval, IntegerVector E, NumericVector gammai, double w0, double alpha);
RcppExport SEXP _onlineFDR_lordstar_async_faster(SEXP pvalSEXP, SEXP ESEXP, SEXP gammaiSEXP, SEXP w0SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type E(ESEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammai(gammaiSEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(lordstar_async_faster(pval, E, gammai, w0, alpha));
    return rcpp_result_gen;
END_RCPP
}
// lordstar_dep_faster
DataFrame lordstar_dep_faster(NumericVector pval, IntegerVector L, NumericVector gammai, double w0, double alpha);
RcppExport SEXP _onlineFDR_lordstar_dep_faster(SEXP pvalSEXP, SEXP LSEXP, SEXP gammaiSEXP, SEXP w0SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type L(LSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammai(gammaiSEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(lordstar_dep_faster(pval, L, gammai, w0, alpha));
    return rcpp_result_gen;
END_RCPP
}
// lordstar_batch_faster
List lordstar_batch_faster(NumericVector pval, IntegerVector batch, IntegerVector batchsum, NumericVector gammai, double w0, double alpha);
RcppExport SEXP _onlineFDR_lordstar_batch_faster(SEXP pvalSEXP, SEXP batchSEXP, SEXP batchsumSEXP, SEXP gammaiSEXP, SEXP w0SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type batch(batchSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type batchsum(batchsumSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammai(gammaiSEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(lordstar_batch_faster(pval, batch, batchsum, gammai, w0, alpha));
    return rcpp_result_gen;
END_RCPP
}
// saffron_faster
DataFrame saffron_faster(NumericVector pval, NumericVector gammai, double lambda, double alpha, double w0);
RcppExport SEXP _onlineFDR_saffron_faster(SEXP pvalSEXP, SEXP gammaiSEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP w0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pval(pvalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gammai(gammaiSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type w0(w0SEXP);
    rcpp_result_gen = Rcpp::wrap(saffron_faster(pval, gammai, lambda, alpha, w0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_onlineFDR_addis_sync_faster", (DL_FUNC) &_onlineFDR_addis_sync_faster, 6},
    {"_onlineFDR_addis_async_faster", (DL_FUNC) &_onlineFDR_addis_async_faster, 7},
    {"_onlineFDR_alphainvesting_faster", (DL_FUNC) &_onlineFDR_alphainvesting_faster, 4},
    {"_onlineFDR_lond_faster", (DL_FUNC) &_onlineFDR_lond_faster, 4},
    {"_onlineFDR_londstar_async_faster", (DL_FUNC) &_onlineFDR_londstar_async_faster, 4},
    {"_onlineFDR_londstar_dep_faster", (DL_FUNC) &_onlineFDR_londstar_dep_faster, 4},
    {"_onlineFDR_londstar_batch_faster", (DL_FUNC) &_onlineFDR_londstar_batch_faster, 5},
    {"_onlineFDR_lord_faster", (DL_FUNC) &_onlineFDR_lord_faster, 7},
    {"_onlineFDR_lordstar_async_faster", (DL_FUNC) &_onlineFDR_lordstar_async_faster, 5},
    {"_onlineFDR_lordstar_dep_faster", (DL_FUNC) &_onlineFDR_lordstar_dep_faster, 5},
    {"_onlineFDR_lordstar_batch_faster", (DL_FUNC) &_onlineFDR_lordstar_batch_faster, 6},
    {"_onlineFDR_saffron_faster", (DL_FUNC) &_onlineFDR_saffron_faster, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_onlineFDR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
